[package]
name = "bibliofile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub = "1.2.2"
ncurses = "5.101.0"
soup = "0.5.1"
